### PR TITLE
10 clean up some old references where the code is named to target a specific pokemon by number need to be renamed

### LINKED ISSUE #10: clean up some old references where the code is named to target a specific pokemon by number need to be renamed.
- [ ] search for "p1" will locate code where I was intending to duplicate then rename to p2 p3 p4 .    We no longer need this naming convention.
- [ ] search for "pokemon1" and "pokemon 1" for the name issue.  for example we are logging that pokemon 1 is KO even if pokemon 2 was actually the one that was KO
```
function isP1KO(pkmn, pkmnNbr) {
    if (pkmn.damage !== 0 && pkmn.hp !== 0 && pkmn.damage >= pkmn.hp) {
        // alert('pokemon KO')
        p1isKO = true;
        console.log('pokemon 1 is KO');
```

### PR DESCRIPTION
**Pull request by thepika206**
sorry for the weird branch name - it was created from an GH issue.

- [x] when a Pokemon is KO, the console print should indicate the correct pokemon # , instead of pokemon 1 is K
- [x] all other functionality is unchanged
- [x] no more code with the naming convention "p1...something" as we won't need to duplicate this code and rename it for each card

- [x] please review the is KO function, why do we need to pass the 2nd parameter "pkmnNbr"?   it looks like pkmn.id will give the same result.  If so we can simply further!

### CODE REVIEW

**Comment by dibujobies** [comment]
@thepika206 git pull to update your local branch. simplified inputs for isKO function. deleted a couple extra console.logs, added pokemon # (not necessarily the variable) to other logs (HP function, clear button)

**Comment by thepika206** [comment]
@dibujobies your changes look good to me.   Are we ready to merge this PR now?

**Comment by dibujobies** [comment]
yep merging now

**Comment by dibujobies** [comment]
git pull this repo. changes merged

**Pull request merged**
