### PR TITLE
Add pkmn

### PR DESCRIPTION
**Pull request by dibujobies**
### Issue:
potential html bloat if 6 cards are to be tracked

### Description
Support for tracking 6 cards has been added:
1. button to add cards to document ('field') added
2. function to dynamically create card divs, buttons, and event listeners added
3. original card html has been removed and replaced with auto-execution of function in (2)
4. array of card Objects to eventually track other states added

### Affects
app.js
index.html

### Checks
- [x] limit of 6 cards
- [x] card damage, HP, and KO states are separate

### After merge
- [x] delete branch
- [x] inform others to update local repos

### CODE REVIEW

**Comment by thepika206** [comment]
can we dump the old variables  at @line12 ?

let p1Dmg = 0;
let p1HP = 0;
let p1isKO = false;

**Comment by thepika206** [comment]
we could also rename  the function name now that it's no longer specific to a pokemon.   
`function isP1KO(pkmn, pkmnNbr)`

maybe 
`function isPkmnKO(pkmn, pkmnNbr)`

**Comment by dibujobies** [comment]
went with isKO(). lots of variables with pokemon or pkmn haha

**Review by thepika206 — APPROVED** [review]
Everything seems to work except that the message printed to the console for KO references Poke 1 exclusively.   This due to my legacy code, so we can fix later.

**Comment by thepika206** [comment]
@dibujobies - I merged "Add pkmn" - reminder to update local repos

**Pull request merged**
